### ISSUE TITLE
Todo 도메인 설계

### ISSUE THREAD

**Issue by tlarbals824** [Kusitms-29th-ASAP/Backend#35]
### 작업 상세 내용

- [x] 조회 api
- [x] 사용자 직접 추가 api
    - [ ] 직접 추가한 todo는 제거가능
- [x] 알림장 기반으로 선생님이 todo 추가 api
